[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "lastmile_utils"
version = "0.0.12"
authors = [
    { name="Jonathan Lessinger", email="jonathan@lastmileai.dev" },
]
description = "Shared LM Python Libraries"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
"Homepage" = "https://github.com/lastmile-ai/lastmile_utils"
"Bug Tracker" = "https://github.com/lastmile-ai/lastmile_utils/issues"